apiVersion: v1
kind: Service
metadata:
  name: otel-prometheus-proxy
spec:
  type: NodePort
  selector:
    app: otel-prometheus-proxy
  ports:
    - name: remote-write
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
